module.exports = {
	name: {
		first: 'David',
		middle: 'Seunghyun',
		last: 'Choi',
	},
	birthday: '1988-07-13',
	email: 'me@davidschoi.com',
	website: 'https://www.davidschoi.com/',
	twitter: 'https://twitter.com/thegreatgumz',
	github: 'https://github.com/greatgumz',
	linkedin: 'https://www.linkedin.com/in/greatgumz/',
	experience: [
		{
			employer: 'Lyft',
			title: 'Senior Software Engineer',
			start: '10/2021',
			end: '04/2023',
		},
		{
			employer: 'Carta',
			title: 'Senior Software Engineer',
			start: '01/2021',
			end: '09/2021',
		},
		{
			employer: 'Self-employed',
			title: 'Web Development Consultant',
			start: '09/2016',
			end: 'present',
		},
		{
			employer: 'Twitch',
			title: 'Front End Engineer II',
			start: '03/2018',
			end: '01/2021',
		},
		{
			employer: 'Solver',
			title: 'Developer',
			start: '01/2017',
			end: '02/2018',
		},
		{
			employer: 'Switchfly',
			title: 'Web Developer',
			start: '09/2012',
			end: '08/2016',
		},
		{
			employer: 'Sungevity',
			title: 'Technical Sales Associate',
			start: '07/2011',
			end: '09/2012',
		},
	],
	education: {
		college: 'University of California, Berkeley',
		graduated: 'May 2011',
		degree: 'Bachelor of Arts',
		major: 'Sociology',
		gpa: '3.7',
	},
	location: 'Orange County, CA',
};
