module.exports = {
	name: {
		first: 'David',
		middle: 'Seunghyun',
		last: 'Choi',
	},
	birthday: '1988-07-13',
	email: 'me@davidschoi.com',
	website: 'https://www.davidschoi.com/',
	twitter: 'https://twitter.com/thegreatgumz',
	github: 'https://github.com/greatgumz',
	linkedin: 'https://www.linkedin.com/in/greatgumz/',
	experience: [
		{
			employer: 'Lyft',
			title: 'Senior Software Engineer',
			start: '10/2021',
			end: '04/2023',
		},
		{
			employer: 'Twitch',
			title: 'Front End Engineer II',
			start: '03/2018',
			end: '01/2021',
		},
		{
			employer: 'Solver',
			title: 'Developer',
			start: '01/2017',
			end: '02/2018',
		},
		{
			employer: 'Switchfly',
			title: 'Web Developer',
			start: '09/2012',
			end: '08/2016',
		},
		{
			employer: 'Sungevity',
			title: 'Technical Sales Associate',
			start: '07/2011',
			end: '09/2012',
		},
	],
	contracting: [
		{
			employer: 'Yahoo Sports',
			description: 'Built new React Player Card using new Sports Design System methodologies. Worked with multiple stakeholders to update Fantasy Football Draft Recaps and Matchup Recaps to utilize ChatGPT generated content, update charts/graphs, email templates, moderation, add mobile responsiveness, and brought in updated React components into PHP application.',
			title: 'Web Developer',
			start: '05/2023',
			end: '05/2024',
		},
		{
			employer: 'Rye',
			description: 'Web lead for building Rye SDK, search demo site using remix, and console dashboard. Migrated to monorepo and contributed to re-architecting data pipelines, models, and API interfaces allowing to integrate with other platforms for 3rd party developers to consume.',
			title: 'Web Lead',
			start: '04/2023',
			end: '05/2023',
		},
		{
			employer: 'Carta',
			description: 'Implemented new instance of carta.com and set up front end architecture using Gatsby, TypeScript, Contentful, ChakraUI; worked with SRE writing lambda function to properly deploy first SPA at Carta on existing Jenkins, AWS S3 Cloudfront, and Terraform pipeline. Migrated Wordpress site to Contentful using Gatsby and bringing our Performance, Accessibility, Best Practices, SEO to 95+ scores and a 1 second time to interactive and a 2 minute build time. Wrote node scripts to automate Wordpress to Contentful migration of 1000+ pages and 5000+ assets converting HTML > Markdown/Rich Text and referencing of media assets, iframes, and 3rd party tools. Integrated 3rd party products like Google Analytics, Amplitude, Looker, Segment, and Marketo to submit forms, track data, and get a better grasp of our customers while standardizing our data.',
			title: 'Senior Software Engineer',
			start: '01/2021',
			end: '09/2021',
		},
		{
			employer: 'Bitwarden',
			description: 'Built, maintained, and later migrated Node, Ruby, Jekyll website and deployment to Contentful deployed via Netlify and updated tech to TypeScript, GatsbyJS, GraphQL.',
			title: 'Web Developer',
			start: '04/2020',
			end: '07/2021',
		},
		{
			employer: 'MinistryPlatform | Think Ministry',
			description: 'Led frontend architecture redesign building design system and creating web components to build scalable widgets.',
			title: 'Frontend Architect',
			start: '07/2019',
			end: '05/2020',
		},
		{
			employer: 'Thinkful',
			description: 'Mentored students in the fundamentals of modern web development in HTML, CSS, and JavaScript; provided code reviews, QA, pair programming, general support and career guidance for students leading web development careers leading to 16 engineering offers.',
			title: 'Mentor',
			start: '10/2016',
			end: '09/2019',
		},
		{
			employer: 'Bridge Financial Technology',
			description: 'Migrated monolith to microservices Angular architecture.',
			title: 'Web Developer',
			start: '04/2019',
			end: '06/2019',
		},
		{
			employer: 'CPQ Solutions',
			description: 'Built boilerplate frontend to optimize the UI/UX customer experience of our base CPQ platform, which converted into quicker deployment and development, shorter training for clients/developers; configure and script CPQ Cloud application based on client design.',
			title: 'Web Developer',
			start: '09/2016',
			end: '04/2017',
		},
	],
	education: {
		college: 'University of California, Berkeley',
		graduated: 'May 2011',
		degree: 'Bachelor of Arts',
		major: 'Sociology',
		gpa: '3.7',
	},
	location: 'Orange County, CA',
};
